version: '3.8'
volumes:
  data:

services:
  postgres:
    image: postgres:15.3
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
  app:
    build: ./
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
    container_name: unicontrol
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - postgres
